### PR TITLE
Footer Added

### PR DESCRIPTION
**Pull request by rohan26062001**
You can tell if you want to change the design, I've just added the footer
image

### CODE REVIEW

**Comment by rohan26062001** [comment]
Header Also Added
image

**Comment by Buddhad** [comment]
You did really good but you should clear these conflicts that you made.
then I gonna merge.

**Comment by rohan26062001** [comment]
Actually, the positions of the files were not proper. Like package-lock.json was outside e the main folder. I've made the necessary changes, now one can just simply clone the repo and run the 'npm install' and then 'npm start' there will be no error that I faced at the time of mine.

**Comment by Buddhad** [comment]
At first, do the fetch upstream and pull all the files and then add all your files then it will work.

**Pull request closed without merging**
